.test:
  before_script:
    - mkdir build
    - cd build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ctest --build-config Debug --output-on-failure

windows:
  extends: .test
  tags:
    - windows

linux:
  extends: .test
  tags:
    - docker
  image: rikorose/gcc-cmake

linux_no_zstd:
  extends: linux
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DLIGHT_USE_ZSTD=OFF
    - cmake --build . --config Release
    - ctest --build-config Release --output-on-failure
