.test:
  before_script:
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan --force
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DLIGHT_USE_ZSTD=OFF
    - cmake --build . --config Debug
    - ctest --build-config Debug --output-on-failure

windows:
  extends: .test
  tags:
    - windows

linux:
  extends: .test
  tags:
    - docker
  image: rikorose/gcc-cmake
  before_script:
    - apt update
    - apt install -y python3-pip
    - pip3 install conan
